from TermTk import TTkUtil, TTkUiLoader, TTk

# Data generated using ttkDesigner
widget = TTkUiLoader.loadDict(
{'version': '2.0.0', 'tui': {'class': 'TTkContainer', 'params': {'Name': 'Application', 'Position': [4, 2], 'Size': [181, 52], 'Min Width': 181, 'Min Height': 52, 'Max Width': 181, 'Max Height': 52, 'Visible': True, 'Enabled': True, 'ToolTip': '', 'Padding': [0, 0, 0, 0], 'Layout': 'TTkLayout'}, 'layout': {'class': 'TTkLayout', 'params': {'Geometry': (0, 0, 181, 52)}, 'children': [{'class': 'TTkFrame', 'params': {'Name': 'left_frame', 'Position': [2, 1], 'Size': [95, 50], 'Min Width': 0, 'Min Height': 0, 'Max Width': 65536, 'Max Height': 65536, 'Visible': True, 'Enabled': True, 'ToolTip': '', 'Padding': [1, 1, 1, 1], 'Layout': 'TTkLayout', 'Border': True, 'Title': ''}, 'layout': {'class': 'TTkLayout', 'params': {'Geometry': (0, 0, 93, 48)}, 'children': []}, 'row': 0, 'col': 0, 'rowspan': 1, 'colspan': 1}, {'class': 'TTkFrame', 'params': {'Name': 'frame_right_top', 'Position': [98, 1], 'Size': [81, 35], 'Min Width': 0, 'Min Height': 0, 'Max Width': 65536, 'Max Height': 65536, 'Visible': True, 'Enabled': True, 'ToolTip': '', 'Padding': [1, 1, 1, 1], 'Layout': 'TTkLayout', 'Border': True, 'Title': ''}, 'layout': {'class': 'TTkLayout', 'params': {'Geometry': (0, 0, 79, 33)}, 'children': []}, 'row': 0, 'col': 0, 'rowspan': 1, 'colspan': 1}, {'class': 'TTkFrame', 'params': {'Name': 'frame_right_bottom', 'Position': [98, 36], 'Size': [81, 15], 'Min Width': 0, 'Min Height': 0, 'Max Width': 65536, 'Max Height': 65536, 'Visible': True, 'Enabled': True, 'ToolTip': '', 'Padding': [1, 1, 1, 1], 'Layout': 'TTkLayout', 'Border': True, 'Title': ''}, 'layout': {'class': 'TTkLayout', 'params': {'Geometry': (0, 0, 79, 13)}, 'children': []}, 'row': 0, 'col': 0, 'rowspan': 1, 'colspan': 1}]}}, 'connections': []})

root=TTk()
root.layout().addWidget(widget)
root.mainloop()
